---

- meta: flush_handlers

- name: Create a network
  become: true
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ filebeat_docker_networks }}"

- name: Start or restart filebeat container
  become: true
  docker_container:
    name: "{{ filebeat_container_name }}"
    image: docker.elastic.co/beats/filebeat:6.6.2
    state: "{{ filebeat_docker_state | default('started') }}"
    restart: "{{ filebeat_docker_restart | default(false) | bool }}"
    networks: "{{ filebeat_docker_networks }}"
    restart_policy: "{{ filebeat_container_restart_policy }}"
    user: root
    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ filebeat_conf_location }}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"

- name: load filebeat template index
  become: true
  uri:
    url: http://localhost:9200/_template/filebeat-6.6.2
    method: PUT
    body: "{{ lookup('file','../templates/filebeat_template.json') }}"
    body_format: json
    headers:
      kbn-xsrf: true