---

- name: load logstash conf file content
  become: true
  set_fact:
    aura_logstash_conf_file_content: "{{ lookup('template', 'logstash.conf.j2') }}"

- include_role:
    name: .galaxy/ansible-logstash-in-docker
  vars:
    logstash_container_name: "{{ aura_logstash_container }}"
    logstash_conf_file_content: "{{ aura_logstash_conf_file_content }}"
    logstash_data_location: "/opt/docker-data/{{ aura_backend_webserver_container }}/data/todo"
    logstash_data_container_location: "{{ aura_logstash_data_container_location }}"
    logstash_docker_networks:
      - name: "{{ aura_docker_network }}"
