---

- name: create logstash local directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ logstash_pipeline_location }}"

- name: create configuration
  become: true
  notify: restart logstash
  template:
    src: "logstash.conf.j2"
    dest: "{{ logstash_pipeline_location }}/logstash.conf"

- name: create logs files
  become: true
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - "/home/ansible/influxdb_manual_logs-json.log"

- include_tasks: run_container.yml
