---

- name: create logstash local directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ logstash_conf_location }}"
    - "{{ logstash_data_location }}"

- name: Create IP_influx variable
  shell: "sudo docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' {{ influxdb_container_name }}"
  register: logstash_influxDB_ip

- name: "Create configuration"
  become: true
  template:
    src: logstash.conf.j2
    dest: "{{ logstash_conf_location }}/logstash.conf"


- name: Ansible copy directory with tests files to the remote server
  copy:
     src: "{{ role_path }}/files/data_example/"
     dest: "{{ logstash_data_location }}"
     owner: "root"
     group: "root"
  become: yes


- include_role:
    name: .galaxy/ansible-logstash-in-docker
  vars:
    logstash_container_name: "{{ aura_logstash_container }}"
    logstash_docker_networks:
      - name: "{{ aura_docker_network }}"

