---

- name: create logstash local directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ logstash_conf_location }}"
    - "{{ logstash_data_location }}"


- name: "Create configuration"
  become: true
  template:
    src: logstash.conf.j2
    dest: "{{ logstash_conf_location }}/logstash.conf"


- include_role:
    name: .galaxy/ansible-logstash-in-docker
  vars:
    logstash_container_name: "{{ aura_logstash_container }}"
    logstash_docker_networks:
      - name: "{{ aura_docker_network }}"

- name: Ansible copy directory with tests files to the remote server
  copy:
     src: "{{ test_data_location }}"
     dest: "/opt/docker-data/{{ aura_logstash_container }}/data"
     mode: "777"
     owner: "root"
     group: "root"
  become: yes