---

airflow_container_name: "airflow"

airflow_root_location: "/opt/docker-data/{{ airflow_container_name }}"
airflow_script_location_test: "{{ airflow_root_location }}/script"
airflow_data_input_location_test: "/opt/docker-data/{{ aura_backend_webserver_container }}/data/todo"
airflow_data_output_success_location_test: "{{ airflow_root_location }}/data/success"
airflow_data_output_failed_location_test: "{{ airflow_root_location }}/data/failed"
airflow_requirements_location_test: "{{ airflow_root_location }}/requirements"

airflow_python_script_name: "dag_raw_data_injector.py"
airflow_python_injector_methods_script_name: "influxdb_raw_data_injector.py"

# variables inside container
airflow_script_location_in_container: "/usr/local/airflow/dags/"
airflow_data_input_location_in_container: "/home/data_test/"
airflow_data_output_success_location_in_container: "/home/write_complete/"
airflow_data_output_failed_location_in_container: "/home/problem_files/"
airflow_requirements_location_in_container: "/usr/local/airflow/requirements/"

airflow_docker_networks: []
#airflow_docker_networks:
#  - name: "docker_network"

airflow_container_restart_policy: "always"