---

- include_role:
    name: .galaxy/ansible-influxdb-in-docker
  vars:
    influxdb_container_name: "{{ aura_time_series_db_container }}"
    influxdb_docker_networks:
      - name: "{{ aura_docker_network }}"

- name: Install influxdb python module
  become: true
  pip:
    name: "influxdb"
    state: present

- name: Get influxdb IP
  become: true
  changed_when: false
  shell: docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' {{ aura_time_series_db_container }}
  register : influxdb_ip

- name: Create database in influxdb
  influxdb_database:
    hostname: "{{ influxdb_ip.stdout }}"
    database_name: "{{ aura_physio_data_db_name }}"

- name: launch RR-interval, MotionAccelerometer and MotionGyroscope Continuous Queries
  become: true
  command: docker exec influxdb influx -execute '{{ item }}'
  with_items:
    - CREATE CONTINUOUS QUERY rri_count_by_day ON {{aura_physio_data_db_name}} BEGIN SELECT count(RrInterval) INTO "rri_count_by_day" FROM "RrInterval" GROUP BY time(1d), "user" END
    - CREATE CONTINUOUS QUERY x_acm_count_by_day ON {{aura_physio_data_db_name}} BEGIN SELECT count("x_acm") INTO "x_acm_count_by_day" FROM "MotionAccelerometer" GROUP BY time(1d), "user" END
    - CREATE CONTINUOUS QUERY y_acm_count_by_day ON {{aura_physio_data_db_name}} BEGIN SELECT count("y_acm") INTO "y_acm_count_by_day" FROM "MotionAccelerometer" GROUP BY time(1d), "user" END
    - CREATE CONTINUOUS QUERY z_acm_count_by_day ON {{aura_physio_data_db_name}} BEGIN SELECT count("z_acm") INTO "z_acm_count_by_day" FROM "MotionAccelerometer" GROUP BY time(1d), "user" END
    - CREATE CONTINUOUS QUERY x_gyro_count_by_day ON {{aura_physio_data_db_name}} BEGIN SELECT count("x_gyro") INTO "x_gyro_count_by_day" FROM "MotionGyroscope" GROUP BY time(1d), "user" END
    - CREATE CONTINUOUS QUERY y_gyro_count_by_day ON {{aura_physio_data_db_name}} BEGIN SELECT count("y_gyro") INTO "y_gyro_count_by_day" FROM "MotionGyroscope" GROUP BY time(1d), "user" END
    - CREATE CONTINUOUS QUERY z_gyro_count_by_day ON {{aura_physio_data_db_name}} BEGIN SELECT count("z_gyro") INTO "z_gyro_count_by_day" FROM "MotionGyroscope" GROUP BY time(1d), "user" END

