---

- include_role:
    name: .galaxy/ansible-influxdb-in-docker
  vars:
    influxdb_container_name: "{{ aura_time_series_db_container }}"
    influxdb_docker_networks:
      - name: "{{ aura_docker_network }}"
