---

- include_role:
    name: .galaxy/ansible-influxdb-in-docker
  vars:
    influxdb_container_name: "{{ aura_time_series_db_container }}"
    influxdb_docker_networks:
      - name: "{{ aura_docker_network }}"

- name: Install influxdb python module
  become: true
  pip:
    name: "influxdb"
    state: present

- name: Get influxdb IP
  become: true
  changed_when: false
  shell: docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' {{ aura_time_series_db_container }}
  register : influxdb_ip

- name: Create database in influxdb
  influxdb_database:
    hostname: "{{ influxdb_ip.stdout }}"
    database_name: "{{ aura_physio_data_db_name }}"
