---

- include_role:
    name: .galaxy/ansible-influxdb-in-docker
  vars:
    influxdb_container_name: "{{ aura_time_series_db_container }}"
    influxdb_docker_networks:
      - name: "{{ aura_docker_network }}"

- name: Create database in influxdb
  become: true
  shell: "docker exec {{ aura_time_series_db_container }} influx -execute 'CREATE DATABASE {{ aura_physio_data_db_name }}';"
