---

aura_docker_network: "skynet"

aura_time_series_db_container: "influxdb"
aura_jupyter_container: "jupyterhub"
aura_logstash_container: "logstash"
aura_backend_webserver_container: "websocket-server"
aura_monitoring_platform_container: "grafana"

aura_time_series_db_port: 8086
aura_physio_data_db_name: "physio_signals"
aura_time_series_db_type: "influxdb"

aura_physio_data_db_name: "physio_signals"

jupyter_url: 'https://explore.{{ domain }}'

jupyter_authorized_users:
  - BastienF
  - BenSchannes
  - clecoued
  - flobreton
  - laudeon
  - lribiere
  - sluslu
  - tbrien
  - Udyrfrykte

grafana_dashboards_location_on_host: "/opt/docker-data/{{ aura_monitoring_platform_container }}/dashboards/"