---

- meta: flush_handlers

- name: Create a network
  become: true
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ kibana_docker_networks }}"

- name: Start or restart kibana container
  become: true
  docker_container:
    name: "{{ kibana_container_name }}"
    image: kibana:6.6.2
    state: "{{ kibana_docker_state | default('started') }}"
    restart: "{{ kibana_docker_restart | default(false) | bool }}"
    networks: "{{ kibana_docker_networks }}"
    restart_policy: "{{ kibana_container_restart_policy }}"
    volumes:
      - "{{ kibana_conf_location }}/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    ports:
      - "5601:5601"

- name: Wait for kibana startup
  wait_for_connection:
    delay: 120
    timeout: 300

- name: load container monitoring dashboard with REST API
  become: true
  uri:
    url: http://192.168.33.22:5601/api/kibana/dashboards/import
    method: POST
    body: "{{ lookup('file','../templates/container_monitoring_dashboard.json.j2') }}"
    body_format: json
    headers:
      kbn-xsrf: true
