---
galaxy_info:
  author: rgirard
  description: Deploy Elasticsearch in docker
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (MIT)


  min_ansible_version: 2.3
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
   - name: EL
     versions:
     - all
   - name: GenericUNIX
     versions:
     - all
   - name: Fedora
     versions:
     - all
   - name: Amazon
     versions:
     - all
   - name: GenericBSD
     versions:
     - all
   - name: FreeBSD
     versions:
     - all
   - name: Ubuntu
     versions:
     - all
   - name: SLES
     versions:
     - all
   - name: GenericLinux
     versions:
     - all
   - name: Debian
     versions:
     - all
   - name: MacOSX
     versions:
     - all
 
  galaxy_tags:
    - docker
    - elasticsearch
#dependencies:
    #- role: base/docker
    #- role: base/ansible_dependencies
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
