---

- include_role:
    name: .galaxy/ansible-airflow-in-docker
  vars:
    airflow_container_name: "airflow"
    airflow_script_location: "{{ airflow_script_location_test }}"
    airflow_data_input_location: "{{ airflow_data_input_location_test }}"
    airflow_data_output_success_location: "{{ airflow_data_output_success_location_test }}"
    airflow_data_output_failed_location: "{{ airflow_data_output_failed_location_test }}"
    airflow_docker_networks:
      - name: "{{ aura_docker_network }}"

- name: Copy requirements file
  become: true
  synchronize:
    src: files/
    dest: "{{ airflow_requirements_location_test }}"
    delete: yes

# TODO : restart container to pip install the custom requirements

- name : Copy templated python script
  become: true
  template: src="templates/{{ airflow_python_script_name }}" dest="{{ airflow_script_location_test }}/{{ airflow_python_script_name }}" mode=0644

# TODO : launch test command "airflow test raw_data_injector write_data 2018-01-01"
