---

dependencies:
    - role: base/docker
    - role: base/ansible_dependencies
      dependency_roles:
        - src: "git+https://github.com/lribiere/ansible-role-websocket-server-in-docker"
          version: master
