---

- name: Update distribution
  become: true
  yum: name=* state=latest


- name: Install yum-utils
  become: true
  yum:
    name: yum-utils

- name: groupinstall development
  become: true
  yum:
    name: "@development"

- name: Install IUS release
  become: true
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: Install python 3.6
  become: true
  yum:
    name: python36u

- name: Install python 3.6 pip
  become: true
  yum:
    name: python36u-pip

- name: Install pandas using pip3.6 environment
  become: true
  pip:
    name: pandas==0.23.4
    executable: pip3.6

- name: Install numpy using pip3.6 environment
  become: true
  pip:
    name: numpy==1.15.2
    executable: pip3.6

- name: Install influxdb using pip3.6 environment
  become: true
  pip:
    name: influxdb==5.2.0
    executable: pip3.6

- name: create elasticsearch local directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "manual_data_injection"
    - "data_generation"

- name: copy data_generation
  become: true
  synchronize:
    src: "{{ path_to_aura_directory }}/Aura_infrastructure/roles/base/prerequisite/files/data_generation"
    dest: "/home/ansible"

- name: copy manual_data_injection
  become: true
  synchronize:
    src: "{{ path_to_aura_directory }}/Aura_infrastructure/roles/base/prerequisite/files/manual_data_injection"
    dest: "/home/ansible"