{
 "title": "Accelerometer dashboard",
 "time": { "from": "2018-07-03T13:36:01.618Z", "to": "2018-07-03T17:30:39.536Z" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "user",
    "query": "SHOW TAG VALUES FROM MotionAccelerometer WITH KEY = \"user\""
   }
  ]
 },
 "panels": [
  { "title": "Raw Accelerometer data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "X-axis accelerometer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"x_acm\" FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/)  AND time >= '2018-07-03 10:00:00' AND time < '2018-07-03 20:00:00'  GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Y-axis accelerometer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"y_acm\" FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND time >= '2018-07-03 10:00:00' AND time < '2018-07-03 20:00:00' GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Z-axis accelerometer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"z_acm\" FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND time >= '2018-07-03 10:00:00' AND time < '2018-07-03 20:00:00' GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accelerometer data count per minute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "X-axis values count per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "user" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "MotionAccelerometer",
       "query": "SELECT count(\"x_acm\") FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY time(1m), \"user\" fill(none)",
       "select": [
        [
         { "params": [ "x_acm" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user", "operator": "=~", "value": "/^$user$/" }
       ]
      }
     ]
    },
    {
     "title": "Y-axis values count per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"y_acm\") FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY time(1m), \"user\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Z-axis values count per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"y_acm\") FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY time(1m), \"user\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}