{
 "title": "Home Dashboard",
 "time": { "from": "now-100d", "to": "now" },
 "panels": [
  {
   "title": "Total number of user in study with RR-interval data",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "query": "SHOW TAG VALUES CARDINALITY FROM \"RrInterval\" WITH KEY = \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total number of user in study with Accelerometer and Gyroscope data",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES CARDINALITY FROM \"MotionAccelerometer\" WITH KEY = \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rr Interval monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Rr Interval count by user",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Total Rr Interval count\" FROM \"rri_count_by_day\" GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Rr Interval count by user filtered by timeFilter",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Rr Interval count\" FROM \"rri_count_by_day\" WHERE $timeFilter GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "alias" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "User count with at least 21000 Rr Interval points (5h) per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "User count" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"rri_count_by_day\" WHERE \"count\" > 21000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "User count with less than 21000 Rr Intervals (5h) per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"rri_count_by_day\" WHERE \"count\" < 21000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Accelerometer monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total accelerometer data count by user",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Total X-acm count\" FROM \"x_acm_count_by_day\" GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Total Y-acm count\" FROM \"y_acm_count_by_day\" GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Total Z-acm count\" FROM \"z_acm_count_by_day\" GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Accelerometer data count by user by time filter",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"X-acm count\" FROM \"x_acm_count_by_day\" WHERE $timeFilter GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Y-acm count\" FROM \"y_acm_count_by_day\" WHERE $timeFilter GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Z-acm count\" FROM \"z_acm_count_by_day\" WHERE $timeFilter GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "User count with at least 630000 ACM points (5h) per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"x_acm_count_by_day\" WHERE \"count\" > 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"y_acm_count_by_day\" WHERE \"count\" > 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"z_acm_count_by_day\" WHERE \"count\" > 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "User count with less than 630000 accelerometer data points (5h) per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "User count" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"x_acm_count_by_day\" WHERE \"count\" < 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"y_acm_count_by_day\" WHERE \"count\" < 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"z_acm_count_by_day\" WHERE \"count\" < 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gyroscope monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total gyroscope data count by user",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Total X-gyro count\" FROM \"x_gyro_count_by_day\" GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Total Y-gyro count\" FROM \"y_gyro_count_by_day\" GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Total Z-gyro count\" FROM \"z_gyro_count_by_day\" GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Gyroscope data count by user on time filter period",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"X-gyro count\" FROM \"x_gyro_count_by_day\" WHERE $timeFilter GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Y-gyro count\" FROM \"y_gyro_count_by_day\" WHERE $timeFilter GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"count\") AS \"Z-gyro count\" FROM \"z_gyro_count_by_day\" WHERE $timeFilter GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "User count with at least 630000 gyroscope data points (5h) per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"x_gyro_count_by_day\" WHERE \"count\" > 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"y_gyro_count_by_day\" WHERE \"count\" > 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"z_gyro_count_by_day\" WHERE \"count\" > 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "User count with less than 630000 gyroscope data points (5h) per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"x_gyro_count_by_day\" WHERE \"count\" < 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"y_gyro_count_by_day\" WHERE \"count\" < 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"count\") FROM \"z_gyro_count_by_day\" WHERE \"count\" < 630000 GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}