{
 "title": "Motion Gyroscope dashboard",
 "time": { "from": "2018-07-05T07:59:38.555Z", "to": "2018-07-05T18:01:15.529Z" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "user",
    "query": "SHOW TAG VALUES FROM MotionGyroscope WITH KEY = \"user\""
   }
  ]
 },
 "panels": [
  { "title": "Raw Gyroscope Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "x gyroscope",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MotionGyroscope",
     "query": "SELECT mean(\"x_gyro\") FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND time >= '2018-07-05 10:00:00' and time < '2018-07-05 20:00:00' GROUP BY time(10s), \"user\" fill(null)",
     "select": [
      [
       { "params": [ "x_gyro" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "y gyroscope",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"y_gyro\" FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND time >= '2018-07-05 10:00:00' and time < '2018-07-05 20:00:00'  GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "z gyroscope",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"z_gyro\" FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND time >= '2018-07-05 10:00:00' and time < '2018-07-05 20:00:00'  GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gyroscope count per minute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "X axis MotionGyroscope count per minute",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "user" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "MotionGyroscope",
       "query": "SELECT count(\"x_gyro\") FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY time(1m), \"user\" fill(none)",
       "select": [
        [
         { "params": [ "x_gyro" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user", "operator": "=~", "value": "/^$user$/" }
       ]
      }
     ]
    },
    {
     "title": "Y axis MotionGyroscope count per minute",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"y_gyro\") FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY time(1m), \"user\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Z axis MotionGyroscope count per minute",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"z_gyro\") FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY time(1m), \"user\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gyroscope count per day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gyroscope points count per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"x_gyro\") FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY time(1d), \"user\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}