{
 "title": "Outliers dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "user",
    "query": "SHOW TAG VALUES FROM MotionAccelerometer WITH KEY = \"user\""
   }
  ]
 },
 "panels": [
  {
   "title": "Summary informations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RrIntervals outliers count by user",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"RrInterval\") AS \"Rr Interval count\" FROM \"RrInterval\" WHERE (\"RrInterval\" < 300 OR \"RrInterval\" > 2000) GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"x_acm\") AS \"X-ACMcount\" FROM \"MotionAccelerometer\" WHERE (\"x_acm\" < -2 OR \"x_acm\" > 2) GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"y_acm\") AS \"Y-ACMcount\" FROM \"MotionAccelerometer\" WHERE (\"y_acm\" < -2 OR \"y_acm\" > 2) GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"z_acm\") AS \"Z-ACMcount\" FROM \"MotionAccelerometer\" WHERE (\"z_acm\" < -2 OR \"z_acm\" > 2) GROUP BY \"user\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Outliers analysis by user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RrInterval outlier count by day for specific user",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"RrInterval\") AS \"Rr Interval count\" FROM \"RrInterval\" WHERE (\"user\" =~ /^$user$/) AND (\"RrInterval\" < 300 OR \"RrInterval\" > 2000)  AND $timeFilter GROUP BY \"user\",  time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Outliers count for accelerometer data by day for specific user",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"x_acm\") AS \"X-ACM count\" FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND (\"x_acm\" < -2 OR \"x_acm\" > 2)  AND $timeFilter GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"y_acm\") AS \"Y-ACM count\" FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND (\"y_acm\" < -2 OR \"y_acm\" > 2)  AND $timeFilter GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"z_acm\") AS \"Z-ACM count\" FROM \"MotionAccelerometer\" WHERE (\"user\" =~ /^$user$/) AND (\"z_acm\" < -2 OR \"z_acm\" > 2)  AND $timeFilter GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Outliers count for Gyroscope data by day for specific user",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"x_gyro\") AS \"X-Gyro count\" FROM \"MotionGyroscope\" WHERE  (\"user\" =~ /^$user$/) AND (\"x_gyro\" < -500 OR \"x_gyro\" > 500)  AND $timeFilter GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"y_gyro\") AS \"Y-Gyro count\" FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND (\"y_gyro\" < -500 OR \"y_gyro\" > 500)  AND $timeFilter GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"z_gyro\") AS \"Z-Gyro count\" FROM \"MotionGyroscope\" WHERE (\"user\" =~ /^$user$/) AND (\"z_gyro\" < -500 OR \"z_gyro\" > 500)  AND $timeFilter GROUP BY time(1d)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}