{
 "title": "Rr Interval dashboard",
 "time": { "from": "now-90d", "to": "now-70d" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "user",
    "query": "SHOW TAG VALUES FROM RrInterval WITH KEY = \"user\""
   }
  ]
 },
 "panels": [
  {
   "title": "Mean Rr Interval per min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RrInterval",
     "query": "SELECT * FROM \"RrInterval\"",
     "select": [
      [
       { "params": [ "RrInterval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "RrInterval count per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RrInterval",
     "query": "SELECT count(\"RrInterval\") FROM \"autogen\".\"RrInterval\" WHERE (\"user\" = 'select tag value') GROUP BY time(10m)",
     "select": [
      [
       { "params": [ "RrInterval" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "Rr Intervals count by day for each user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RrInterval",
     "select": [
      [
       { "params": [ "RrInterval" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "RR-intervals data count by user",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "RrInterval",
     "query": "SELECT count(\"RrInterval\") FROM \"RrInterval\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "RrInterval" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  }
 ]
}