---

- meta: flush_handlers

- name: Create a network
  become: true
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ metricbeat_docker_networks }}"

- name: Start or restart metricbeat container
  become: true
  docker_container:
    name: "{{ metricbeat_container_name }}"
    image: docker.elastic.co/beats/metricbeat:6.7.0
    state: "{{ metricbeat_docker_state | default('started') }}"
    restart: "{{ metricbeat_docker_restart | default(false) | bool }}"
    networks: "{{ metricbeat_docker_networks }}"
    restart_policy: "{{ metricbeat_container_restart_policy }}"
    user: root
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ metricbeat_conf_location }}/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
