---

dependencies:
    - role: base/docker
    - role: base/ansible_dependencies
      dependency_roles:
        - src: "git+https://github.com/souf989/ansible-logstash-in-docker"
          version: master
