---

- name: Get info about jupyterhub container
  become: true
  command: docker container inspect jupyterhub
  changed_when: false
  register: docker_container_jupyterhub_result

- name: Parse info about jupyterhub container
  set_fact:
    docker_container_jupyterhub_info: "{{ docker_container_jupyterhub_result.stdout | from_json | first }}"

- include_role:
    name: .galaxy/ansible-traefik-in-docker
  vars:
    traefik_http_port: 80
    traefik_http_admin_port: 8080
    traefik_https_port: 443
    traefik_le_staging: false
    traefik_endpoints:
      influxdb:
        host: "db.aura.healthcare"
        dest: "http://193.251.229.249:8086"
        host_gen_cert: true
      jupyterhub:
        host: "explore.aura.healthcare"
        dest: "http://{{ docker_container_jupyterhub_info.NetworkSettings.IPAddress }}:8000"
        host_gen_cert: true
