---

- name: Get info about jupyterhub container
  become: true
  command: docker container inspect jupyterhub
  changed_when: false
  register: docker_container_jupyterhub_result

- name: Get info about influxdb container
  become: true
  command: docker container inspect influxdb
  changed_when: false
  register: docker_container_influxdb_result


- name: Parse info about containers
  set_fact:
    docker_container_jupyterhub_info: "{{ docker_container_jupyterhub_result.stdout | from_json | first }}"
    docker_container_influxdb_info: "{{ docker_container_influxdb_result.stdout | from_json | first }}"

- include_role:
    name: .galaxy/ansible-traefik-in-docker
  vars:
    traefik_http_port: 80
    traefik_http_admin_port: 8080
    traefik_https_port: 443
    traefik_le_staging: "{{ is_prod|default(false)|bool }}"
    traefik_endpoints:
      influxdb:
        host: "db.{{ domain }}"
        dest: "http://{{ docker_container_influxdb_info.NetworkSettings.IPAddress }}:8086"
        host_gen_cert: true
      jupyterhub:
        host: "explore.{{ domain }}"
        dest: "http://{{ docker_container_jupyterhub_info.NetworkSettings.IPAddress }}:8000"
        host_gen_cert: true
