---

- include_role:
    name: .galaxy/ansible-traefik-in-docker
  vars:
    traefik_docker_networks:
      - name: "{{ aura_docker_network }}"
    traefik_http_port: 80
    traefik_http_admin_port: 8080
    traefik_https_port: 443
    traefik_le_staging: "{{ not (is_prod|default(false)|bool) }}"
    traefik_endpoints:
      traefik:
        host: "proxy.{{ domain }}"
        dest: "http://localhost:8080"
        host_gen_cert: true
      influxdb:
        host: "db.{{ domain }}"
        dest: "http://{{ aura_time_series_db_container }}:{{ aura_time_series_db_port }}"
        host_gen_cert: true
      jupyterhub:
        host: "explore.{{ domain }}"
        dest: "http://{{ aura_jupyter_container }}:8000"
        host_gen_cert: true
      websocket_server:
        host: "data.{{ domain }}"
        dest: "ws://{{ aura_backend_webserver_container }}:8887"
        host_gen_cert: true
      grafana:
        host: "monitor.{{ domain }}"
        dest: "http://{{ aura_monitoring_platform_container }}:3000"
        host_gen_cert: true
      airflow:
        host: "scheduler.{{ domain }}"
        dest: "http://airflow_localexecutor_webserver_1:8080"
        host_gen_cert: true
