---

aura_airflow_container_name: "airflow"
aura_airflow_root_location: "/opt/docker-data/{{ aura_airflow_container_name }}"

aura_airflow_script_location: "{{ aura_airflow_root_location }}/script"
aura_airflow_data_input_location: "/opt/docker-data/{{ aura_backend_webserver_container }}/data/todo"
aura_airflow_data_output_success_location: "/opt/docker-data/{{ aura_backend_webserver_container }}/data/success"
aura_airflow_data_output_failed_location: "/opt/docker-data/{{ aura_backend_webserver_container }}/data/failed"
aura_airflow_requirements_location: "{{ aura_airflow_root_location }}/requirements"

airflow_python_raw_data_injector_methods_script_name: "influxdb_raw_data_injector.py"
airflow_python_energy_injector_methods_script_name: "energy_injector_methods.py"
airflow_python_raw_data_dag_name: "dag_raw_data_injector.py"
airflow_python_energy_dag_name: "dag_energy_injector.py"

# variables inside container for Python files
airflow_data_input_location_in_container: "/usr/local/airflow/todo/"
airflow_data_output_success_location_in_container: "/usr/local/airflow/write_complete/"
airflow_data_output_failed_location_in_container: "/usr/local/airflow/problem_files/"

airflow_container_restart_policy: "always"
