---

- meta: flush_handlers

- name: Create a network
  become: true
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ elasticsearch_docker_networks }}"

- name: Start or restart elasticsearch container
  become: true
  docker_container:
    name: "{{ elasticsearch_container_name }}"
    image: elasticsearch:6.6.2
    state: "{{ elasticsearch_docker_state | default('started') }}"
    restart: "{{ elasticsearch_docker_restart | default(false) | bool }}"
    networks: "{{ elasticsearch_docker_networks }}"
    restart_policy: "{{ elasticsearch_container_restart_policy }}"
    volumes:
      - "{{ elasticsearch_conf_location }}/elasticsearch.yml:/config/elasticsearch.yml:ro"
    ports:
      - "9200:9200"
      - "9300:9300"
