---

- name: create logspout local directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ logspout_conf_location }}"

- include_tasks: run_container.yml