---

- meta: flush_handlers

- name: Create a network
  become: true
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ logspout_docker_networks }}"

- name: Start or restart logspout container
  become: true
  become_method: sudo
  docker_container:
    name: "{{ logspout_container_name }}"
    image: bekt/logspout-logstash
    state: "{{ logspout_docker_state | default('started') }}"
    restart: "{{ logspout_docker_restart | default(false) | bool }}"
    networks: "{{ logspout_docker_networks }}"
    restart_policy: "{{ logspout_container_restart_policy }}"
    env:
      ROUTE_URIS: logstash://logstash:5000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
